// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function AddProduct(arg1:string,arg2:number,arg3:number,arg4:string):Promise<void>;

export function DelProduct(arg1:number):Promise<void>;

export function List():Promise<Array<model.Product>>;

export function UpdateProduct(arg1:number,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;
