// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProduct(arg1, arg2, arg3, arg4) {
  return window['go']['product']['Service']['AddProduct'](arg1, arg2, arg3, arg4);
}

export function DelProduct(arg1) {
  return window['go']['product']['Service']['DelProduct'](arg1);
}

export function List() {
  return window['go']['product']['Service']['List']();
}

export function UpdateProduct(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['product']['Service']['UpdateProduct'](arg1, arg2, arg3, arg4, arg5);
}
