// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PlaceCartelaPurchase(arg1) {
  return window['go']['purchase']['Service']['PlaceCartelaPurchase'](arg1);
}

export function PlacePurchase(arg1) {
  return window['go']['purchase']['Service']['PlacePurchase'](arg1);
}
