// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function PlaceCartelaPurchase(arg1:model.Purchase):Promise<void>;

export function PlacePurchase(arg1:model.Purchase):Promise<void>;
