// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetReportData() {
  return window['go']['report']['Service']['GetReportData']();
}

export function PrintReport() {
  return window['go']['report']['Service']['PrintReport']();
}
