// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {report} from '../models';

export function GetReportData():Promise<report.ReportPage>;

export function PrintReport():Promise<void>;
