// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelarPedido(arg1) {
  return window['go']['main']['App']['CancelarPedido'](arg1);
}

export function ClonarEvento(arg1) {
  return window['go']['main']['App']['ClonarEvento'](arg1);
}

export function CreateEvento(arg1, arg2) {
  return window['go']['main']['App']['CreateEvento'](arg1, arg2);
}

export function CreateGrupo(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateGrupo'](arg1, arg2, arg3);
}

export function CreateProduto(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CreateProduto'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CriarPedido(arg1) {
  return window['go']['main']['App']['CriarPedido'](arg1);
}

export function DeleteEvento(arg1) {
  return window['go']['main']['App']['DeleteEvento'](arg1);
}

export function DeleteGrupo(arg1) {
  return window['go']['main']['App']['DeleteGrupo'](arg1);
}

export function DeleteProduto(arg1) {
  return window['go']['main']['App']['DeleteProduto'](arg1);
}

export function FecharPedido(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FecharPedido'](arg1, arg2, arg3, arg4);
}

export function GetDBPath() {
  return window['go']['main']['App']['GetDBPath']();
}

export function GetLarguraLinha() {
  return window['go']['main']['App']['GetLarguraLinha']();
}

export function GetModoDebug() {
  return window['go']['main']['App']['GetModoDebug']();
}

export function GetPedido(arg1) {
  return window['go']['main']['App']['GetPedido'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImprimirTexto(arg1) {
  return window['go']['main']['App']['ImprimirTexto'](arg1);
}

export function ListCartelas() {
  return window['go']['main']['App']['ListCartelas']();
}

export function ListContas(arg1) {
  return window['go']['main']['App']['ListContas'](arg1);
}

export function ListContasSaldo(arg1) {
  return window['go']['main']['App']['ListContasSaldo'](arg1);
}

export function ListEventos() {
  return window['go']['main']['App']['ListEventos']();
}

export function ListGrupos(arg1) {
  return window['go']['main']['App']['ListGrupos'](arg1);
}

export function ListImpressoras() {
  return window['go']['main']['App']['ListImpressoras']();
}

export function ListPedidos(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListPedidos'](arg1, arg2, arg3, arg4);
}

export function ListPedidosConta(arg1) {
  return window['go']['main']['App']['ListPedidosConta'](arg1);
}

export function ListProdutos(arg1) {
  return window['go']['main']['App']['ListProdutos'](arg1);
}

export function ListProdutosVenda(arg1) {
  return window['go']['main']['App']['ListProdutosVenda'](arg1);
}

export function MoverGrupo(arg1, arg2) {
  return window['go']['main']['App']['MoverGrupo'](arg1, arg2);
}

export function MoverProduto(arg1, arg2) {
  return window['go']['main']['App']['MoverProduto'](arg1, arg2);
}

export function OpenDBFolder() {
  return window['go']['main']['App']['OpenDBFolder']();
}

export function QuitarConta(arg1) {
  return window['go']['main']['App']['QuitarConta'](arg1);
}

export function ReorderGrupos(arg1, arg2) {
  return window['go']['main']['App']['ReorderGrupos'](arg1, arg2);
}

export function ReorderProdutos(arg1) {
  return window['go']['main']['App']['ReorderProdutos'](arg1);
}

export function ResumoEvento(arg1) {
  return window['go']['main']['App']['ResumoEvento'](arg1);
}

export function SetImpressora(arg1) {
  return window['go']['main']['App']['SetImpressora'](arg1);
}

export function SetLarguraLinha(arg1) {
  return window['go']['main']['App']['SetLarguraLinha'](arg1);
}

export function SetModoDebug(arg1) {
  return window['go']['main']['App']['SetModoDebug'](arg1);
}

export function SetProdutoAtivo(arg1, arg2) {
  return window['go']['main']['App']['SetProdutoAtivo'](arg1, arg2);
}

export function UpdateEvento(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateEvento'](arg1, arg2, arg3, arg4);
}

export function UpdateGrupo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateGrupo'](arg1, arg2, arg3);
}

export function UpdateProduto(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UpdateProduto'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ZerarBanco() {
  return window['go']['main']['App']['ZerarBanco']();
}
