// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateEvento(arg1:string):Promise<main.Evento>;

export function CreateProduto(arg1:number,arg2:string,arg3:number,arg4:string,arg5:number):Promise<main.Produto>;

export function CriarPedido(arg1:number):Promise<main.Pedido>;

export function DeleteEvento(arg1:number):Promise<void>;

export function DeleteProduto(arg1:number):Promise<void>;

export function FecharPedido(arg1:number,arg2:Array<main.PedidoItem>):Promise<main.Pedido>;

export function GetPedido(arg1:number):Promise<main.Pedido>;

export function Greet(arg1:string):Promise<string>;

export function ListEventos():Promise<Array<main.Evento>>;

export function ListProdutos(arg1:number):Promise<Array<main.Produto>>;

export function ListProdutosVenda(arg1:number):Promise<Array<main.ProdutoVenda>>;

export function SetProdutoAtivo(arg1:number,arg2:boolean):Promise<void>;

export function UpdateEvento(arg1:number,arg2:string,arg3:boolean):Promise<void>;

export function UpdateProduto(arg1:number,arg2:string,arg3:number,arg4:string,arg5:number):Promise<void>;
