// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEvento(arg1) {
  return window['go']['main']['App']['CreateEvento'](arg1);
}

export function CreateProduto(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProduto'](arg1, arg2, arg3, arg4, arg5);
}

export function CriarPedido(arg1) {
  return window['go']['main']['App']['CriarPedido'](arg1);
}

export function DeleteEvento(arg1) {
  return window['go']['main']['App']['DeleteEvento'](arg1);
}

export function DeleteProduto(arg1) {
  return window['go']['main']['App']['DeleteProduto'](arg1);
}

export function FecharPedido(arg1, arg2) {
  return window['go']['main']['App']['FecharPedido'](arg1, arg2);
}

export function GetPedido(arg1) {
  return window['go']['main']['App']['GetPedido'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListEventos() {
  return window['go']['main']['App']['ListEventos']();
}

export function ListProdutos(arg1) {
  return window['go']['main']['App']['ListProdutos'](arg1);
}

export function ListProdutosVenda(arg1) {
  return window['go']['main']['App']['ListProdutosVenda'](arg1);
}

export function SetProdutoAtivo(arg1, arg2) {
  return window['go']['main']['App']['SetProdutoAtivo'](arg1, arg2);
}

export function UpdateEvento(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEvento'](arg1, arg2, arg3);
}

export function UpdateProduto(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProduto'](arg1, arg2, arg3, arg4, arg5);
}
